format = """
[](fg:#9A348E)\
$custom\
[](bg:#DA627D fg:#9A348E)\
$username\
$hostname\
[](fg:#DA627D bg:#FCA17D)\
$directory\
[](fg:#FCA17D bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#06969A)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$python\
[](fg:#06969A bg:#33658A)\
$docker_context\
[ ](fg:#33658A)\
"""

# light cyan : 06969A
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
    show_always = true
    style_user = 'bg:#DA627D fg:#000000'
    style_root = 'bg:#9A348E'
    format = '[$user@]($style)'

[hostname]
    ssh_only = false               # affiche toujours
    trim_at = "."                  # tronque après le premier point (équivalent de %m)
    ssh_symbol = " "
    style = "bg:#DA627D fg:#000000"
    format = "[$hostname]($style)"

[directory]
    style = "bg:#FCA17D fg:#000000"
    format = "[$path]($style)"
    truncation_length = 3
    truncation_symbol = "…/"
    read_only = " 󰌾"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
    "Documents" = "📄 "
    "Downloads" = "📥 "
    "Music" = "🎜 "
    "Pictures" = "📷 "
    
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[python]
    style = 'teal'
    symbol = " " # '🐍 '
    format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
    pyenv_version_name = true
    pyenv_prefix = ''



[docker_context]
    symbol = " " # use starship istead of default : "🐳 " 
    style = "bg:#06969A"
    format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
    symbol = " " # use starship gly^ph instead of default : "💧 "
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[elm]
    symbol = " " # use starship gly^ph instead of default : "🌳 "
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[git_branch]
    symbol = " " # ""
    style = "bg:#FCA17D"
    format = '[[ $symbol $branch ](bg:#86BBD8 fg:#000000)]($style)'

[git_status]
    style = "bg:#FCA17D"
    format = '[[($all_status$ahead_behind )](bg:#86BBD8 fg:#000000)]($style)'

[golang]
    symbol = " " # "🐹 "
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[haskell]
    symbol = " " # "λ "
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[java]
    symbol = " " # "☕"
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[julia]
    symbol = " " # "ஃ "
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[nodejs]
    symbol = " " # "🔷 "
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[nim]
    symbol = "󰆥 " # "👑 "
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'

[rust]
    symbol = "󱘗 " # "🦀"
    style = "bg:#86BBD8"
    format = '[[ $symbol ($version)](bg:#06969A)]($style)'
    
# more symbols (from default config file (see starship website) :   

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "




[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "



[git_commit]
tag_symbol = '  '



[gradle]
symbol = " "

[guix_shell]
symbol = " "



[haxe]
symbol = " "

[hg_branch]
symbol = " "







[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "



[nix_shell]
symbol = " "



[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[scala]
symbol = " "

[status]
symbol = " "

[swift]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "

# ending added symbols

#############################################################
# count idle, working, sleeping time

[time]
    disabled = false
    style = "bg:#33658A"
    format = '[[ ⏰ $time ](bg:#9A348E)]($style)'


###############################################################

# count project lines (when moving repertories it updates)
# require python for number formatting (adding space each 3 char numbers)

#[custom.project_lines]
#    command = """
#    total=$(find . -type f \
#        ! -path '*/.git/*' \
#        ! -path '*/.idea/*' \
#        ! -path '*/node_modules/*' \
#        -exec wc -l {} + 2>/dev/null | awk 'END {print $1}')
#    # if in project ? 
#    [ -z "$total" ] || [ "$total" -eq 0 ] && exit 1
#    # python is present ?
#    if command -v python3 >/dev/null 2>&1; then
#        # format like 21223 into 21 223
#        python3 -c "print(f'{int('$total'):,}'.replace(',',' '))"
#    else
#        echo "$total"
#    fi
#    """
#    when = "test -d ."
#    style = "bg:#9A348E fg:#FDC2FF"    
#    format = "[📝  ${output} lines]($style)"
